_site/about/team/index.html
Reverts zcoinofficial/firo-site#4
=> Revert "Team 2020 Oct"

get-firo/download/index.html, guide/masternode-setup.md, guide/masternode-upgrade.md
Update links et al to v0.14.2.1
=> Update to v0.14.2.1

get-firo/download/index.html, guide/masternode-setup.md, guide/masternode-upgrade.md
=> Revert "Update to v0.14.2.1"

_includes/header.html, about/faq/index.html, css/style.css, guide/index.html
Put guides on guides page
Put guides page on nav bar
=> Added guides page

css/style.css
=> Tried to make list look better

_config.yml, _i18n/en.yml, _i18n/zh-cn.yml, _includes/footer.html, _includes/head.html, _includes/header.html, _layouts/tag.html, about/faq/index.html, about/roadmap/index.html, about/team/index.html, about/tech/index.html, blog/index.html, branding/index.html, community/index.html, get-firo/buy-firo/index.html, get-firo/download/index.html, guide/index.html, index.html
* Initial Chinese localization
* Fixed the Earn Firo link in mobile menu
=> Initial Chinese localization

_i18n/zh-cn.yml
Reference Commit https://github.com/firoorg/firo-site/commit/5f757ae861185769c944eacfe1153a6725535ae8
=> Update roadmap in _i18n/zh-cn.yml

_posts/2021-10-01-new-mandatory-update-01490.md
=> v0.14.9.0 blog post

_i18n/id.yml
Translation credit to Ryan from the Indonesian community.
=> Indonesian translation

_i18n/en.yml, _i18n/id.yml, _i18n/zh-cn.yml, get-firo/download/index.html
Added Stack Wallet to Downloads page
=> Added Stack Wallet to Downloads page

community/merchants/index.html
Link changed to http://bit.do/nownodes-firo as requested
=> update nownodes link

get-firo/buy-firo/index.html
Redirect to Firo changenow page
=> update changenow url

get-firo/download/index.html, guide/masternode-setup.md, guide/masternode-upgrade.md
Do not merge until all download links are tested.
There was a typo in the commit message. The commit itself is fine.
=> Update site to v0.14.12.0

get-firo/download/index.html
=> Revert "Update Firo Client to v3.0.1"

get-firo/download/index.html
Reverted earlier due to mistake
=> Update Firo Client to v3.0.1

get-firo/buy-firo/index.html
remove inactive or closure partners
=> Cleanup getfiro page

_posts/2023-4-19-2nd-community-fund-committee-elected.md
A blog post for the CFC Election of 2023
=> 2023-4-19-2nd-community-fund-committee-elected.md

_includes/head.html
pages without image would just show nothing on social media
=> head: fall back to firo banner if no og:image is specified

_i18n/en.yml, community/merchants/index.html
Closes #233
Add alt texts as for #252
=> merchants: remove broken links and add alt text to images

_layouts/base.html, _layouts/guide.html, _layouts/policy.html, _layouts/post.html
little detail but very important for SEO score and to help search engines indicise the website
=> declare html language in layouts

blog/index.html, css/style.css
The page looks a bit empty. Changed to 2 posts per page instead of 1. On mobile the same 1-post layout is used. I also fixed the messed up indentation in the posts loop
=> blog: show 2 posts for row instead of 1

_i18n/en.yml, community/social/index.html
=> social: add i18n, lazy loading and alt texts

_posts/2023-07-31-lelantus-spark-testnet-launched.md
changed title of trivia and formatting headers
=> Formatting and title changes

_posts/2023-07-31-lelantus-spark-testnet-launched.md
Corrected small spelling mistakes.
Removed mention of CoinMarketCap from Spark Mayhem event
=> 2023-07-31-lelantus-spark-testnet-launched.md

get-firo/buy-firo/index.html
=> buy-firo: clan up missing exchages

css/style.css
=> merchants: add max height and scaling to logos

css/style.css, get-firo/download/index.html
the images disappeared because they were used with the method removed with https://github.com/firoorg/firo-site/pull/292. ~~Still couple of things to fix before merge~~
=> download: fix platform img of third-party wallets

_i18n/id.yml
This translation is based on Indonesian standart rules
=> Update indonesian translation

get-firo/buy-firo/index.html, guide/masternode-setup.md
Removed some exchanges that has gone down.
=> Buy firo cleanup

get-firo/buy-firo/index.html
Fixed missing line above binance line
> <div class="col">
=> Buy Firo Page fix

index.html
removed likely by accident in #351
=> home: bring back alt and lazy loading in images

_i18n/id.yml, _i18n/zh-cn.yml
- fix missing i18n keys
- fix team entries in indonesian
=> fix some i18n strings

community/merchants/index.html
add referral to defi-nation hyperlink
=> Added Referral link

about/research/index.html
=> Quick link fix for papers

guide/masternode-setup.md
Rewrite/update portions of the masternode guide for easier reading/clarity.
=> Masternode guide refactor

css/style.css
=> css: fix styling of code blocks and quotes

guide/firo-migration-guide.md, guide/how-to-mine.md, guide/liquidity-provider-firo-bnb.md, guide/masternode-setup.md, guide/masternode-upgrade.md, guide/reindex-wallet.md
Requires #379
Fixed use of backticks on all user guides which use them.
=> adapt guides to fixed code blocks format

guide/liquidity-provider-firo-bnb.md, guide/masternode-setup.md, guide/reindex-wallet.md, guide/troubleshooting-masternode.md
- Update old link
- Fix formatting in guides
=> Guide formatting fixes

guide/masternode-setup.md
=> Remove Satang from masternode providers list

_posts/2024-05-03-3rd-term-cfc-members-formed.md
=> Update on a sentence in blog

netlify.toml
Netlify needs to be configured for previews to work.
=> add netlify's config

_posts/2024-08-19-final-vote-tokenomics-2024.md
Added linked to related blog links that was missing
=> Correct link Blog

get-firo/buy-firo/index.html
Rearrange some of the exchanges too.
=> Removed Binance

get-firo/buy-firo/index.html
=> Revert "Removed Binance"

get-firo/buy-firo/index.html
fixed missing line which messed up the images
=> Update buy firo

get-firo/buy-firo/index.html
Cyphergoat is an open source crypto exchange aggregator that supports FIRO
=> Add cyphergoat.com instant exchange aggregator

guide/masternode-setup.md
=> Added Higlan to masternode provider
